version: '3'
services:
  dubbo-provider:
    image: hustcyb/cyb-dubbo-provider:1.0.0-SNAPSHOT
    links:
      - zookeeper
    environment:
      - DUBBO_REGISTRY_ADDRESS=zookeeper://zookeeper:2181

  dubbo-comsumer:
    image: hustcyb/cyb-dubbo-consumer:1.0.0-SNAPSHOT
    environment:
      - DUBBO_REGISTRY_ADDRESS=zookeeper://zookeeper:2181
    ports:
      - "8080:8080"
    links:
      - zookeeper


  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"