version: '3'
services:
  dubbo-provider:
    image: hustcyb/cyb-dubbo-provider:1.0.0-SNAPSHOT
    environment:
      DUBBO_REGISTRY_ADDRESS: zookeeper://zoo1:2181?backup=zoo2:2181,zoo3:2181

  dubbo-consumer:
    image: hustcyb/cyb-dubbo-consumer:1.0.0-SNAPSHOT
    environment:
      DUBBO_REGISTRY_ADDRESS: zookeeper://zoo1:2181?backup=zoo2:2181,zoo3:2181
    ports:
      - "8080:8080"

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888